version: '3.7'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - nodeserver
      - flaskserver
    networks:
      - my-network-name
    links:
      - nodeserver
      - flaskserver

  nodeserver:
    build: ./node_server
    container_name: nodeserver
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - my-network-name

  flaskserver:
    build: ./flask
    container_name: flaskserver
    ports:
      - 5001:5000
    expose:
      - "5000"
    networks:
      - my-network-name

networks:
  my-network-name: