version: '3.7'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - nodeserver
    networks:
      - my-network-name
    links:
      - nodeserver

  nodeserver:
    build: ./node_server
    container_name: nodeserver
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - my-network-name

networks:
  my-network-name: